version: 2
updates:
  # for v4-dev branch
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "03:00"
    open-pull-requests-limit: 10
    target-branch: "v4-dev"
    labels:
      - dependencies
      - version:4.x
    versioning-strategy: increase
    rebase-strategy: disabled

  # for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "03:00"
